# Generated by Django 2.0.2 on 2018-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180221_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trainers',
        ),
    ]
