# Generated by Django 2.0.2 on 2018-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_client_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trainers',
            field=models.ManyToManyField(related_name='clients', to='account.Trainer'),
        ),
    ]
