# Generated by Django 2.0.2 on 2018-03-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_client_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttotrainer',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clienttotrainer',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='limit',
        ),
        migrations.AddField(
            model_name='account',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Trainer', 'Trainer')], default='Client', max_length=255),
        ),
        migrations.DeleteModel(
            name='ClientToTrainer',
        ),
    ]
