# Generated by Django 2.0.2 on 2018-03-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_invite_initiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Open', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Trainer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InviteTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Open', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Trainer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='invite',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
