CLIENT = 'Client'
TRAINER = 'Trainer'
MODERATOR = 'Moderator'

ACCOUNT_TYPES = (
    (CLIENT, CLIENT),
    (TRAINER, TRAINER)
)

ACCOUNT_CREATE_MODERATOR_TYPES = (
    (MODERATOR, MODERATOR),
)

OPEN = 'Open'
ACCEPTED = 'Accepted'
REJECTED = 'Rejected'

INVITE_STATUS_TYPES = (
    (ACCEPTED, ACCEPTED),
    (REJECTED, REJECTED)
)
