# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
