# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20160708_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='role',
            field=models.CharField(choices=[(1, 'User'), (2, 'Manager'), (3, 'Admin')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='limit',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
